/**
 * Guard: a route registered as a CHILD of a layout route can only render where that layout
 * renders an <Outlet/>.
 *
 * Why this exists (2026-09-28): /app/subscription/success and /app/subscription/cancel are children
 * of AppRoute (see src/routeTree.gen.ts, `getParentRoute: () => AppRoute`), and src/routes/app.tsx
 * rendered no <Outlet/> at all. So a buyer who had just paid landed on the studio ("Welcome back…")
 * instead of the confirmation page — or, signed out, was redirected to /login with ?session_id=…
 * dropped. Nothing failed: the routes existed, the build passed, and the pages were unreachable.
 * That is the class of bug this check catches structurally.
 *
 * WHAT IT PROVES: for every parent/child relationship in the generated route tree, the parent's
 * source file renders an <Outlet/>, and the two post-payment routes are children of /app and
 * render their own content.
 * WHAT IT CANNOT PROVE: that a running server actually renders it. Only a fetch or a browser
 * against a deployed host proves that.
 *
 * Run: bun scripts/check-layout-outlets.ts
 */
import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const TREE = join(ROOT, "src/routeTree.gen.ts");

const failures: string[] = [];
let checks = 0;

function check(label: string, ok: boolean, detail = "") {
  checks++;
  /* The detail is a failure explanation, so it is only printed when the check fails. */
  console.log(`${ok ? "PASS" : "FAIL"}  ${label}${!ok && detail ? `: ${detail}` : ""}`);
  if (!ok) failures.push(`${label}${detail ? ` — ${detail}` : ""}`);
}

if (!existsSync(TREE)) {
  console.error(`FATAL: ${TREE} not found — the route tree is generated by the build; run \`bun run build\` first.`);
  process.exit(2);
}
const tree = readFileSync(TREE, "utf8");

/* --- generated tree -> source files ------------------------------------------------------- */
/* `import { Route as AppSubscriptionSuccessRouteImport } from './routes/app/subscription/success'` */
const fileByRouteVar = new Map<string, string>();
for (const m of tree.matchAll(/import \{ Route as (\w+) \} from '\.\/routes\/([^']+)'/g)) {
  const [, varSuffix, routePath] = m;
  const varName = varSuffix.replace(/Import$/, "");
  fileByRouteVar.set(varName, `src/routes/${routePath}${routePath.endsWith(".tsx") ? "" : ".tsx"}`);
}
/* The root route lives in the generated file itself; its layout is src/routes/__root.tsx.
 * Generated code refers to it both as `rootRoute` and as `rootRouteImport`. */
fileByRouteVar.set("rootRoute", "src/routes/__root.tsx");
fileByRouteVar.set("rootRouteImport", "src/routes/__root.tsx");

/** Resolve a route variable (generated names carry an `Import` suffix) to its source file. */
function fileForVar(routeVar: string): string | null {
  return fileByRouteVar.get(routeVar) ?? fileByRouteVar.get(routeVar.replace(/Import$/, "")) ?? null;
}

/* --- parent/child edges ------------------------------------------------------------------- */
/* `const AppSubscriptionSuccessRoute = AppSubscriptionSuccessRouteImport.update({ ... getParentRoute: () => AppRoute,`
 * The child var is the LAST `const X =` before its own getParentRoute, so walk the text in order. */
const edges: { child: string; parent: string }[] = [];
let lastConst = "";
for (const line of tree.split("\n")) {
  const constMatch = /^const (\w+) = /.exec(line.trim());
  if (constMatch) lastConst = constMatch[1];
  const parentMatch = /getParentRoute: \(\) => (\w+)/.exec(line);
  if (parentMatch && lastConst) edges.push({ child: lastConst, parent: parentMatch[1] });
}

check("the route tree parsed", edges.length > 0, `${edges.length} parent/child edge(s) found`);

/** Source with comments and import lines stripped: a layout must RENDER an Outlet, not merely
 *  mention one. The first version of this check passed on its own documentation comment, which is
 *  exactly the kind of false pass it exists to prevent. */
function stripNonRendering(source: string): string {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "")
    .replace(/^\s*import[\s\S]*?from\s+"[^"]*";\s*$/gm, "");
}

const readSource = (rel: string): string | null => {
  const abs = join(ROOT, rel);
  return existsSync(abs) ? readFileSync(abs, "utf8") : null;
};

console.log("\n--- Every layout route renders its children ---");
const checkedParents = new Set<string>();
for (const { child, parent } of edges) {
  if (checkedParents.has(parent)) continue;
  checkedParents.add(parent);
  const rel = fileForVar(parent) ?? `(unknown file for ${parent})`;
  const src = readSource(rel);
  check(
    `${parent} (${rel}) renders <Outlet/>`,
    src !== null && /<Outlet\s*\/?>/.test(stripNonRendering(src)),
    src === null
      ? `can't read ${rel} — the layout file for ${parent} could not be resolved`
      : `no <Outlet/> in ${rel}, so every child route registered under it (e.g. ${child}) renders nothing`,
  );
}

console.log("\n--- The post-payment routes are reachable (the 2026-09-28 regression) ---");
const POST_PAYMENT = ["/app/subscription/success", "/app/subscription/cancel"];
const appSource = readSource("src/routes/app.tsx") ?? "";
check(
  "the /app layout renders <Outlet/>",
  /<Outlet\s*\/?>/.test(stripNonRendering(appSource)),
  "src/routes/app.tsx has no <Outlet/>, so a buyer returning from Stripe cannot see a confirmation",
);

for (const path of POST_PAYMENT) {
  const rel = `src/routes${path}.tsx`;
  const src = readSource(rel);
  /* Each of these is a complete page of its own — its own full-height wrapper and navigation —
   * which is why rendering them instead of the studio is safe. */
  check(
    `${path} renders its own page`,
    src !== null && /<Navigation\b/.test(src) && /<h1\b/.test(src),
    src === null ? `${rel} is missing` : `${rel} must render its own layout and heading`,
  );
  check(
    `${path} is registered as a child of /app`,
    edges.some(({ child, parent }) => fileForVar(child) === rel && fileForVar(parent) === "src/routes/app.tsx"),
    `the generated tree does not register ${rel} under src/routes/app.tsx — if that moved, this check is looking in the wrong place`,
  );
  check(
    `${path} does not bounce the buyer to /login`,
    src !== null && !/to: "\/login"/.test(src),
    `${rel} redirects to /login — a buyer returning from checkout may have no session and must still read their confirmation`,
  );
}
check(
  "the /app layout does not send post-payment paths to /login",
  !/isSubscriptionReturn/.test(appSource) || /if \(isSubscriptionReturn\) \{\s*setAuthLoading\(false\);\s*return;/.test(appSource),
  "src/routes/app.tsx computes a subscription-return flag but its auth effect can still redirect to /login, dropping ?session_id=…",
);

console.log(
  "\nNOTE: this proves the layout renders its children and that the post-payment pages exist as\n" +
    "      complete pages. It cannot prove a deployed host serves them — only a fetch or a browser can.",
);

if (failures.length > 0) {
  console.error(`\n${failures.length} FAILURE(S):\n- ${failures.join("\n- ")}`);
  process.exit(1);
}
console.log(`\nAll ${checks} layout-outlet checks passed.`);
