/**
 * Relevate renderer — versioned visual regression + contract test (v1.0.0, 2026-08-12)
 * ===================================================================================
 * Canonical home of the renderer regression suite. Run with:
 *   bun scripts/render-regression.ts        (or: bun run render-regression)
 *
 * Proves the exact client payload → validateRenderRequest → renderMarketingPng
 * path for flyer and social, including:
 *  - multi-line text regions (bullets/contact) auto-fit (regression for the
 *    newline-collapsing overflow bug)
 *  - image-region replacement (prompt/upload path) cover-fitted
 *  - aspect-ratio letterboxing (flyer template on social canvas and vice versa)
 *  - body-omitted template render (validation relaxation)
 *  - branded (no-template) mode still renders
 *  - contract-enum coverage (every fontFamily/fontWeight/label/align a saved
 *    template region can carry must validate and render)
 *  - validation guardrails (4 reject cases)
 *  - FLYER BLEND FIX (owner-approved): per-region background sampling — light
 *    and dark fixtures, contrast guard, foreground sampling, full-pipeline
 *    blend checks, and sampled-lettering override of wrong vision textColor
 *  - output PNG dimension verification (IHDR)
 *
 * HOW TO EXTEND: append a new `run(name, payload, expectPng)` call for
 * payload-path checks, or push directly to `results` for assertion-style
 * checks (see sections 7–8). Keep every existing assertion; add new ones at
 * the end so the check count grows monotonically. Exit code 1 on any ❌/⚠️.
 *
 * FIXTURES: light-template-flyer.png / dark-template-flyer.png live in
 * /home/team/shared/render-samples/ (generated by scripts/make-light-template.ts
 * and scripts/make-dark-template.ts); design-assets in /home/team/shared/design-assets/.
 */
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { renderMarketingPng, validateRenderRequest, sampleRegionBackgrounds, sampleRegionForegrounds } from "../src/lib/render.ts";
import { Resvg } from "@resvg/resvg-js";

const __dirname = dirname(fileURLToPath(import.meta.url)); // scripts/
const SITE = join(__dirname, "..");
const SHARED = join(SITE, ".."); // /home/team/shared
const dir = join(SHARED, "render-samples");
const asset = async (p: string) => `data:image/png;base64,${(await readFile(p)).toString("base64")}`;

const flyerBg = await asset(join(SHARED, "design-assets/flyer-background.png"));
const socialBg = await asset(join(SHARED, "design-assets/social-background.png"));
const photo = await asset(join(SHARED, "design-assets/social-header-band.png"));

const results: string[] = [];
async function run(name: string, payload: Record<string, unknown>, expectPng: boolean) {
  const check = validateRenderRequest(payload);
  if (!check.ok) {
    results.push(`❌ ${name}: validateRenderRequest REJECTED — ${check.error}`);
    return;
  }
  try {
    const dataUrl = await renderMarketingPng(check.data);
    const png = Buffer.from(dataUrl.split(",")[1], "base64");
    await writeFile(`${dir}/${name}.png`, png);
    results.push(`✅ ${name}: validated + rendered (${(png.length / 1024).toFixed(0)} KB, ${expectPng ? "PNG" : "unexpected"})`);
  } catch (err) {
    results.push(`❌ ${name}: render threw — ${err instanceof Error ? err.message : String(err)}`);
  }
}

await mkdir(dir, { recursive: true });

// 1) Flyer replica: multi-line headline + bullets + contact, photo region replaced
await run("template-replica-flyer", {
  type: "flyer",
  title: "2847 Willow Creek Lane",
  body: "Open Saturday 1-4 PM",
  templateImage: flyerBg,
  templateWidth: 1275,
  templateHeight: 1650,
  templateRegions: [
    { id: "headline", kind: "text", label: "headline", x: 0.1, y: 0.16, w: 0.8, h: 0.1, textColor: "#f8f5ec", fontFamily: "serif", fontWeight: "bold", fontSizePx: 64, align: "left" },
    { id: "subheadline", kind: "text", label: "subheadline", x: 0.1, y: 0.27, w: 0.8, h: 0.06, textColor: "#d1fae5", fontFamily: "sans-serif", fontSizePx: 30, align: "left" },
    { id: "photo", kind: "image", label: "photo", x: 0.1, y: 0.36, w: 0.38, h: 0.18 },
    { id: "bullets", kind: "text", label: "bullets", x: 0.1, y: 0.58, w: 0.8, h: 0.2, textColor: "#e5e7eb", fontFamily: "sans-serif", fontSizePx: 26, align: "left" },
    { id: "cta", kind: "text", label: "cta", x: 0.1, y: 0.8, w: 0.8, h: 0.05, textColor: "#d4a017", fontFamily: "sans-serif", fontWeight: "bold", fontSizePx: 28, align: "center" },
    { id: "contact", kind: "text", label: "contact", x: 0.1, y: 0.86, w: 0.8, h: 0.08, textColor: "#f8f5ec", fontFamily: "sans-serif", fontSizePx: 24, align: "center" },
  ],
  regionText: {
    headline: "Modern Living at\n2847 Willow Creek",
    subheadline: "4 beds  •  3 baths  •  2,485 sq ft",
    bullets: "• Sun-filled open floor plan\n• Chef's kitchen with quartz island\n• Primary suite with spa bath\n• Backyard made for entertaining",
    cta: "OPEN SATURDAY 1–4 PM",
    contact: "Maya Chen\n(555) 014-2208  •  maya@relevate.ai",
  },
  regionImages: { photo },
}, true);

// 2) Social replica: multi-line headline/body + image region replacement
await run("template-replica-social-v2", {
  type: "social",
  title: "A Fresh Start in Northwood",
  body: "DM Maya for a tour",
  templateImage: socialBg,
  templateWidth: 1080,
  templateHeight: 1080,
  templateRegions: [
    { id: "headline", kind: "text", label: "headline", x: 0.12, y: 0.14, w: 0.72, h: 0.16, textColor: "#f8f5ec", fontFamily: "serif", fontWeight: "bold", fontSizePx: 54, align: "left" },
    { id: "body", kind: "text", label: "body", x: 0.12, y: 0.4, w: 0.7, h: 0.14, textColor: "#d1fae5", fontFamily: "sans-serif", fontSizePx: 26, align: "left" },
    { id: "photo", kind: "image", label: "photo", x: 0.62, y: 0.58, w: 0.26, h: 0.26 },
  ],
  regionText: {
    headline: "A Fresh Start\nin Northwood",
    body: "Bright 3-bedroom home with an open kitchen and room to gather.\nDM for a private tour.",
  },
  regionImages: { photo },
}, true);

// 3) Body-omitted template render (validation relaxation)
await run("template-replica-no-body", {
  type: "social",
  title: "ignored",
  templateImage: socialBg,
  templateWidth: 1080,
  templateHeight: 1080,
  templateRegions: [
    { id: "headline", kind: "text", label: "headline", x: 0.12, y: 0.3, w: 0.7, h: 0.12, textColor: "#f8f5ec", fontFamily: "sans-serif", fontWeight: "bold", fontSizePx: 60, align: "center" },
  ],
  regionText: { headline: "Your Next Chapter" },
}, true);

// 3b) Contract-enum coverage: every fontFamily/fontWeight/label/align a saved
// template region can carry must validate and render (fullstack contract parity)
await run("template-replica-enums", {
  type: "social",
  title: "ignored",
  body: "ignored",
  templateImage: socialBg,
  templateWidth: 1080,
  templateHeight: 1080,
  templateRegions: [
    { id: "h1", kind: "text", label: "headline", x: 0.1, y: 0.12, w: 0.8, h: 0.1, textColor: "#f8f5ec", fontFamily: "serif", fontWeight: "bold", fontSizePx: 54, align: "left" },
    { id: "b1", kind: "text", label: "body", x: 0.1, y: 0.3, w: 0.8, h: 0.1, textColor: "#e5e7eb", fontFamily: "sans-serif", fontWeight: "light", fontSizePx: 26, align: "center" },
    { id: "c1", kind: "text", label: "cta", x: 0.1, y: 0.48, w: 0.8, h: 0.08, textColor: "#d4a017", fontFamily: "script", fontWeight: "normal", fontSizePx: 30, align: "right" },
    { id: "f1", kind: "text", label: "footer", x: 0.1, y: 0.62, w: 0.8, h: 0.08, textColor: "#9ca3af", fontFamily: "display", fontWeight: "light", fontSizePx: 22, align: "center" },
    { id: "m1", kind: "text", label: "contact", x: 0.1, y: 0.74, w: 0.8, h: 0.08, textColor: "#d1fae5", fontFamily: "mono", fontWeight: "bold", fontSizePx: 24, align: "left" },
    { id: "p1", kind: "image", label: "logo", x: 0.08, y: 0.86, w: 0.12, h: 0.12 },
  ],
  regionText: { h1: "Enum Coverage", b1: "All five font families and weights", c1: "BOOK A TOUR", f1: "display faces map to serif", m1: "mono/light/bold all render" },
  regionImages: { p1: photo },
}, true);

// 4) Letterbox: square template rendered onto flyer canvas (top/bottom bands)
await run("template-replica-flyer-square-template", {
  type: "flyer",
  title: "ignored",
  body: "ignored",
  templateImage: socialBg,
  templateWidth: 1080,
  templateHeight: 1080,
  templateRegions: [
    { id: "headline", kind: "text", label: "headline", x: 0.1, y: 0.2, w: 0.8, h: 0.12, textColor: "#f8f5ec", fontFamily: "sans-serif", fontWeight: "bold", fontSizePx: 56, align: "center" },
  ],
  regionText: { headline: "Replica on Flyer Canvas" },
}, true);

// 5) Letterbox: flyer-aspect template rendered onto social canvas (side bands)
await run("template-replica-social-flyer-template", {
  type: "social",
  title: "ignored",
  body: "ignored",
  templateImage: flyerBg,
  templateWidth: 1275,
  templateHeight: 1650,
  templateRegions: [
    { id: "headline", kind: "text", label: "headline", x: 0.12, y: 0.3, w: 0.76, h: 0.12, textColor: "#f8f5ec", fontFamily: "sans-serif", fontWeight: "bold", fontSizePx: 44, align: "center" },
  ],
  regionText: { headline: "Replica on Social Canvas" },
}, true);

// 6) Branded (no-template) regression — AI-background mode still works
await run("regression-branded-flyer", {
  type: "flyer",
  title: "2847 Willow Creek Lane",
  body: "Open Saturday, 1–4 PM\n\n4 beds • 3 baths • 2,485 sq ft\n\nTour a sun-filled home with an updated kitchen and a backyard made for entertaining.\n\nOffered at $895,000",
  agentName: "Maya Chen | Evergreen Realty",
  brandStyle: "modern minimalist, navy + gold",
}, true);

await run("regression-branded-social", {
  type: "social",
  title: "A Fresh Start in Northwood",
  body: "Just listed: a bright 3-bedroom home with an open kitchen and room to gather.\n\nDM Maya for a private tour.",
  agentName: "Maya Chen | Evergreen Realty",
  imageDataUrl: photo,
}, true);

// 7) Validation rejections (contract guardrails)
const reject1 = validateRenderRequest({ type: "social", title: "x" }); // no template, no body → must reject
const reject2 = validateRenderRequest({ type: "flyer", title: "x", body: "y", templateImage: socialBg, templateRegions: [], regionText: {} }); // empty regions
const validRegion = [{ id: "t", kind: "text", label: "headline", x: 0.2, y: 0.2, w: 0.5, h: 0.1 }];
const reject3 = validateRenderRequest({ type: "flyer", title: "x", body: "y", templateImage: socialBg, templateRegions: validRegion, regionText: { t: "ok", unknown: "bad" } }); // regionText references unknown region
const reject4 = validateRenderRequest({ type: "flyer", title: "x", body: "y", templateImage: socialBg, templateRegions: validRegion, regionText: { t: "ok" }, regionImages: { t: "data:image/png;base64,AAAA" } }); // image given for a TEXT region
results.push(`${reject1.ok ? "⚠️" : "✅"} reject#1 body-required-without-template: ${reject1.ok ? "should reject (actually: passed)" : reject1.error}`);
results.push(`${reject2.ok ? "⚠️" : "✅"} reject#2 empty templateRegions: ${reject2.ok ? "should reject (actually: passed)" : reject2.error}`);
results.push(`${reject3.ok ? "⚠️" : "✅"} reject#3 unknown regionText id: ${reject3.ok ? "should reject (actually: passed)" : reject3.error}`);
results.push(`${reject4.ok ? "⚠️" : "✅"} reject#4 regionImages on text region: ${reject4.ok ? "should reject (actually: passed)" : reject4.error}`);

// ---------------------------------------------------------------------------
// 8) FLYER BLEND FIX (owner-approved): text-region surfaces are sampled from
//    the template's local background. A LIGHT template must render a light
//    region surface (no near-black box); the surface must match the template's
//    own background pixels at the same spot. Social template mode is untouched
//    (byte-identical vs baseline, verified separately).
// ---------------------------------------------------------------------------
const lightFlyer = await asset(join(SHARED, "render-samples/light-template-flyer.png"));
const darkFlyer = await asset(join(SHARED, "render-samples/dark-template-flyer.png"));

function samplePixel(dataUrl: string, width: number, height: number, fx: number, fy: number): [number, number, number] {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><image href="${dataUrl}" x="0" y="0" width="${width}" height="${height}"/></svg>`;
  const rendered = new Resvg(svg).render();
  const px = rendered.pixels;
  const x = Math.max(0, Math.min(width - 1, Math.round(fx * width)));
  const y = Math.max(0, Math.min(height - 1, Math.round(fy * height)));
  const i = (y * width + x) * 4;
  return [px[i], px[i + 1], px[i + 2]];
}
// min/max luminance over an entire region box of the rendered output
function boxLum(dataUrl: string, width: number, height: number, rx: number, ry: number, rw: number, rh: number): { min: number; max: number } {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><image href="${dataUrl}" x="0" y="0" width="${width}" height="${height}"/></svg>`;
  const px = new Resvg(svg).render().pixels;
  const x0 = Math.max(0, Math.round(rx * width)), y0 = Math.max(0, Math.round(ry * height));
  const x1 = Math.min(width - 1, Math.round((rx + rw) * width)), y1 = Math.min(height - 1, Math.round((ry + rh) * height));
  let min = 255, max = 0;
  for (let y = y0; y <= y1; y++) for (let x = x0; x <= x1; x++) {
    const i = (y * width + x) * 4;
    const l = 0.2126 * px[i] + 0.7152 * px[i + 1] + 0.0722 * px[i + 2];
    if (l < min) min = l;
    if (l > max) max = l;
  }
  return { min, max };
}
const lum = (c: [number, number, number]) => 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
const maxDelta = (a: [number, number, number], b: [number, number, number]) => Math.max(Math.abs(a[0] - b[0]), Math.abs(a[1] - b[1]), Math.abs(a[2] - b[2]));
const hexRgb = (hex: string): [number, number, number] => [parseInt(hex.slice(1, 3), 16), parseInt(hex.slice(3, 5), 16), parseInt(hex.slice(5, 7), 16)];

// 8a) Direct sampler unit checks
const lightRegions = [
  { id: "card", kind: "text", label: "headline", x: 0.0706, y: 0.1818, w: 0.847, h: 0.2, textColor: "#3a3a36", fontFamily: "serif", fontWeight: "bold", fontSizePx: 52, align: "left" },
];
const lightSurfaces = sampleRegionBackgrounds(lightFlyer, lightRegions as never, 1275, 1650);
const lightSurfaceLum = lightSurfaces.card ? lum([parseInt(lightSurfaces.card.slice(1, 3), 16), parseInt(lightSurfaces.card.slice(3, 5), 16), parseInt(lightSurfaces.card.slice(5, 7), 16)]) : 0;
results.push(`${lightSurfaces.card && lightSurfaceLum > 180 ? "✅" : "❌"} sampleRegionBackgrounds(light): surface ${lightSurfaces.card || "MISSING"} luminance ${lightSurfaceLum.toFixed(0)} (must be light, >180)`);

// 8b) Contrast guard: white textColor on an EMPTY light region (no lettering to
//     sample → falls back to vision color) must darken the surface
const guardSurfaces = sampleRegionBackgrounds(lightFlyer, [{ id: "t", kind: "text", label: "headline", x: 0.1, y: 0.5, w: 0.8, h: 0.1, textColor: "#ffffff" }] as never, 1275, 1650);
const guardLum = guardSurfaces.t ? lum(hexRgb(guardSurfaces.t)) : 0;
results.push(`${guardSurfaces.t && guardLum < 130 ? "✅" : "❌"} contrast-guard: surface ${guardSurfaces.t || "MISSING"} luminance ${guardLum.toFixed(0)} (must darken for white text, <130)`);

// 8e) Foreground sampler unit — LIGHT template: original lettering must be dark
//     (≈ the template's #3a3a36 headline, within tolerance)
const lightFgs = sampleRegionForegrounds(lightFlyer, lightRegions as never, 1275, 1650);
const lightFgLum = lightFgs.card ? lum(hexRgb(lightFgs.card)) : 0;
const lightFgClose = lightFgs.card ? maxDelta(hexRgb(lightFgs.card), [58, 58, 54]) : 999;
results.push(`${lightFgs.card && lightFgLum < 100 && lightFgClose < 60 ? "✅" : "❌"} sampleRegionForegrounds(light): fg ${lightFgs.card || "MISSING"} lum ${lightFgLum.toFixed(0)} delta ${lightFgClose.toFixed(0)} vs #3a3a36 (must be dark ≈ template lettering)`);

// 8f) Foreground sampler unit — DARK template: original lettering must be light
//     (≈ the template's cream #f2e9d0, within tolerance)
const darkCardRegions = [
  { id: "card", kind: "text", label: "headline", x: 0.0706, y: 0.1818, w: 0.847, h: 0.2 },
];
const darkFgs = sampleRegionForegrounds(darkFlyer, darkCardRegions as never, 1275, 1650);
const darkFgLum = darkFgs.card ? lum(hexRgb(darkFgs.card)) : 0;
const darkFgClose = darkFgs.card ? maxDelta(hexRgb(darkFgs.card), [242, 233, 208]) : 999;
results.push(`${darkFgs.card && darkFgLum > 180 && darkFgClose < 60 ? "✅" : "❌"} sampleRegionForegrounds(dark): fg ${darkFgs.card || "MISSING"} lum ${darkFgLum.toFixed(0)} delta ${darkFgClose.toFixed(0)} vs #f2e9d0 (must be light ≈ template lettering)`);

// 8c) Full pipeline on the LIGHT template → output region surface must be light
//     and ≈ the template's own background at the same spot (blends, no black box)
const lightPayload = {
  type: "flyer", title: "ignored", body: "ignored",
  templateImage: lightFlyer, templateWidth: 1275, templateHeight: 1650,
  templateRegions: lightRegions,
  regionText: { card: "2847 Willow Creek Lane\nSaturday 1–4 PM  •  4 beds  •  3 baths" },
};
const lightCheck = validateRenderRequest(lightPayload);
if (lightCheck.ok) {
  const dataUrl = await renderMarketingPng(lightCheck.data);
  const png = Buffer.from(dataUrl.split(",")[1], "base64");
  await writeFile(`${dir}/blend-fix-light-flyer.png`, png);
  const probe = { fx: 0.0706 + 0.06 * 0.847, fy: 0.1818 + 0.06 * 0.2 };
  const out = samplePixel(dataUrl, 1275, 1650, probe.fx, probe.fy);
  const tpl = samplePixel(lightFlyer, 1275, 1650, probe.fx, probe.fy);
  const outLum = lum(out);
  const blend = outLum > 180;
  const close = maxDelta(out, tpl) < 70;
  results.push(`${blend && close ? "✅" : "❌"} blend-fix-light-flyer: output region ${out.join(",")} lum ${outLum.toFixed(0)} vs template ${tpl.join(",")} ${blend ? "LIGHT (no black box) ✓" : "STILL BLACK BOX ✗"} ${close ? "matches template ✓" : "MISMATCH ✗"}`);
} else {
  results.push(`❌ blend-fix-light-flyer: validation rejected — ${lightCheck.error}`);
}

// 8d) Dark template sanity: region surface still dark (blends with dark design)
const darkPayload = {
  type: "flyer", title: "ignored", body: "ignored",
  templateImage: flyerBg, templateWidth: 1275, templateHeight: 1650,
  templateRegions: [
    { id: "headline", kind: "text", label: "headline", x: 0.1, y: 0.16, w: 0.8, h: 0.1, textColor: "#f8f5ec", fontFamily: "serif", fontWeight: "bold", fontSizePx: 64, align: "left" },
  ],
  regionText: { headline: "2847 Willow Creek Lane" },
};
const darkCheck = validateRenderRequest(darkPayload);
if (darkCheck.ok) {
  const dataUrl = await renderMarketingPng(darkCheck.data);
  const out = samplePixel(dataUrl, 1275, 1650, 0.1 + 0.06 * 0.8, 0.16 + 0.06 * 0.1);
  const tpl = samplePixel(flyerBg, 1275, 1650, 0.1 + 0.06 * 0.8, 0.16 + 0.06 * 0.1);
  const outLum = lum(out);
  const close = maxDelta(out, tpl) < 70;
  results.push(`${outLum < 100 && close ? "✅" : "❌"} blend-fix-dark-flyer: output ${out.join(",")} lum ${outLum.toFixed(0)} vs template ${tpl.join(",")} ${close ? "blends ✓" : "MISMATCH ✗"}`);
} else {
  results.push(`❌ blend-fix-dark-flyer: validation rejected — ${darkCheck.error}`);
}

// 8g) Full pipeline LIGHT with a DELIBERATELY WRONG vision textColor (#ff00ff):
//     the sampled template lettering must override it → rendered glyphs are DARK
//     (min box luminance < 80) on the light surface, not magenta
const wrongColorPayload = {
  type: "flyer", title: "ignored", body: "ignored",
  templateImage: lightFlyer, templateWidth: 1275, templateHeight: 1650,
  templateRegions: [
    { id: "card", kind: "text", label: "headline", x: 0.0706, y: 0.1818, w: 0.847, h: 0.2, textColor: "#ff00ff", fontFamily: "serif", fontWeight: "bold", fontSizePx: 52, align: "left" },
  ],
  regionText: { card: "2847 Willow Creek Lane\nSaturday 1–4 PM  •  4 beds  •  3 baths" },
};
const wrongLight = validateRenderRequest(wrongColorPayload);
if (wrongLight.ok) {
  const dataUrl = await renderMarketingPng(wrongLight.data);
  const png = Buffer.from(dataUrl.split(",")[1], "base64");
  await writeFile(`${dir}/text-color-light-flyer.png`, png);
  const { min } = boxLum(dataUrl, 1275, 1650, 0.0706, 0.1818, 0.847, 0.2);
  results.push(`${min < 80 ? "✅" : "❌"} text-color-light-flyer: glyph min lum ${min.toFixed(0)} < 80 → sampled DARK lettering overrode wrong #ff00ff ✓`);
} else {
  results.push(`❌ text-color-light-flyer: validation rejected — ${wrongLight.error}`);
}

// 8h) Full pipeline DARK with a deliberately wrong vision textColor (#ff00ff):
//     sampled template lettering (cream) must override it → rendered glyphs are
//     LIGHT (max box luminance > 180) on the dark surface
const wrongDarkPayload = {
  type: "flyer", title: "ignored", body: "ignored",
  templateImage: darkFlyer, templateWidth: 1275, templateHeight: 1650,
  templateRegions: [
    { id: "card", kind: "text", label: "headline", x: 0.0706, y: 0.1818, w: 0.847, h: 0.2, textColor: "#ff00ff", fontFamily: "serif", fontWeight: "bold", fontSizePx: 52, align: "left" },
  ],
  regionText: { card: "2847 Willow Creek Lane\nSaturday 1–4 PM  •  4 beds  •  3 baths" },
};
const wrongDark = validateRenderRequest(wrongDarkPayload);
if (wrongDark.ok) {
  const dataUrl = await renderMarketingPng(wrongDark.data);
  const png = Buffer.from(dataUrl.split(",")[1], "base64");
  await writeFile(`${dir}/text-color-dark-flyer.png`, png);
  const { max } = boxLum(dataUrl, 1275, 1650, 0.0706, 0.1818, 0.847, 0.2);
  results.push(`${max > 180 ? "✅" : "❌"} text-color-dark-flyer: glyph max lum ${max.toFixed(0)} > 180 → sampled CREAM lettering overrode wrong #ff00ff ✓`);
} else {
  results.push(`❌ text-color-dark-flyer: validation rejected — ${wrongDark.error}`);
}

// Verify output PNG dimensions by reading IHDR of each written file
const files = (await readdir(dir)).filter((f) => f.startsWith("template-replica-") || f.startsWith("regression-") || f.startsWith("blend-fix-") || f.startsWith("text-color-"));
for (const f of files) {
  const buf = await readFile(`${dir}/${f}`);
  if (buf.length > 24 && buf.toString("ascii", 1, 4) === "PNG") {
    const w = buf.readUInt32BE(16);
    const h = buf.readUInt32BE(20);
    results.push(`📐 ${f}: ${w}×${h}`);
  }
}

console.log(results.join("\n"));
const failed = results.filter((r) => r.includes("❌") || r.includes("⚠️"));
console.log(`\n${results.length - failed.length}/${results.length} checks passed`);
process.exit(failed.length ? 1 : 0);
